# Restart rsyslog after updating this file: systemctl restart rsyslog
# outchannel format: name,file,size,rotate-cmd
$outchannel kbdtoe,/var/log/kbdtoe/kbdtoe.log,2097152,/usr/sbin/logrotate /etc/logrotate.d/kbdtoe
$FileCreateMode 0600

if $programname contains 'libkbdtoe' then {
    :omfile:$kbdtoe
    stop
}
