# 修改配置后需重启：systemctl restart rsyslog
# 定义了使用微秒时间戳的模板
# $outchannel [定向符号],[定向输出文件],[输出文件限制大小],[转储指令]
# [输出文件限制大小]需要与logrotate配置的size项一致
# 转储文件数目由logrotatd.d/knet中rotate约束

$template WithMicroseconds,"%TIMESTAMP%.%timestamp:::date-subseconds% %HOSTNAME% %syslogtag%%msg%\n"

$outchannel knet,/var/log/knet/knet_comm.log,2097152,/usr/sbin/logrotate /etc/logrotate.d/knet
$FileCreateMode 0600

if $programname contains 'libknet' then {
    :omfile:$knet;WithMicroseconds
    stop
}